### ISSUE TITLE
Error after fresh install

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-magento#100]
After a fresh install, I get this error when trying to go to the full-results page. FYI, I never saved the Algolia Search configuration.

```
a:5:{i:0;s:57:"Invalid parameter or missing value: removeWordsIfNoResult";i:1;s:3691:"#0 /var/www/htdocs/.modman/algoliasearch-magento/code/Helper/AlgoliaSearch/Client.php(383): AlgoliaSearch\Client->doRequest(Object(AlgoliaSearch\ClientContext), 'GET', 'sylvain-dsn.alg...', '/1/indexes/mage...', Array, NULL, 2, 5)
#1 /var/www/htdocs/.modman/algoliasearch-magento/code/Helper/AlgoliaSearch/Index.php(295): AlgoliaSearch\Client->request(Object(AlgoliaSearch\ClientContext), 'GET', '/1/indexes/mage...', Array, NULL, Array, 2, 5)
#2 /var/www/htdocs/.modman/algoliasearch-magento/code/Helper/Algoliahelper.php(36): AlgoliaSearch\Index->search('as', Array)
#3 /var/www/htdocs/.modman/algoliasearch-magento/code/Helper/Data.php(61): Algolia_Algoliasearch_Helper_Algoliahelper->query('magento19_defau...', 'as', Array)
#4 /var/www/htdocs/.modman/algoliasearch-magento/code/Model/Resource/Fulltext/Collection.php(23): Algolia_Algoliasearch_Helper_Data->getSearchResult('as', '1')
#5 /var/www/htdocs/app/code/core/Mage/CatalogSearch/Model/Layer.php(58): Algolia_Algoliasearch_Model_Resource_Fulltext_Collection->addSearchFilter('as')
#6 /var/www/htdocs/app/code/core/Mage/CatalogSearch/Model/Layer.php(42): Mage_CatalogSearch_Model_Layer->prepareProductCollection(Object(Algolia_Algoliasearch_Model_Resource_Fulltext_Collection))
#7 /var/www/htdocs/app/code/core/Mage/Catalog/Model/Layer.php(290): Mage_CatalogSearch_Model_Layer->getProductCollection()
#8 /var/www/htdocs/app/code/core/Mage/Catalog/Model/Layer.php(220): Mage_Catalog_Model_Layer->_getSetIds()
#9 /var/www/htdocs/app/code/core/Mage/Catalog/Block/Layer/View.php(163): Mage_Catalog_Model_Layer->getFilterableAttributes()
#10 /var/www/htdocs/app/code/core/Mage/Catalog/Block/Layer/View.php(122): Mage_Catalog_Block_Layer_View->_getFilterableAttributes()
#11 /var/www/htdocs/app/code/core/Mage/Core/Block/Abstract.php(293): Mage_Catalog_Block_Layer_View->_prepareLayout()
#12 /var/www/htdocs/app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#13 /var/www/htdocs/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('catalogsearch/l...', 'catalogsearch.l...')
#14 /var/www/htdocs/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('catalogsearch/l...', 'catalogsearch.l...')
#15 /var/www/htdocs/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#16 /var/www/htdocs/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#17 /var/www/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#18 /var/www/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#19 /var/www/htdocs/app/code/core/Mage/CatalogSearch/controllers/ResultController.php(77): Mage_Core_Controller_Varien_Action->loadLayout()
#20 /var/www/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_CatalogSearch_ResultController->indexAction()
#21 /var/www/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#22 /var/www/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#23 /var/www/htdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#24 /var/www/htdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#25 /var/www/htdocs/index.php(87): Mage::run('', 'store')
```

**Comment by maxiloc** [comment]
I think I fixed it. Just waiting for the docker instance to run to check if it worked :)

**Comment by redox** [comment]
Yes it works now.
