### ISSUE TITLE
Upgrading to new version from 1.6.0 to 1.14.0 effectively brings down entire site with exception: AlgoliaSearch requires an apiKey

### ISSUE THREAD

**Issue by ProxiBlue** [algolia/algoliasearch-magento#1048]
**Do you want to request a *feature* or report a *bug*?**

Reporting a bug

**Bug: What is the current behavior?**

Upgrading via composer from old version 1.6.0 to 1.14.0 kills site with error exception report:

AlgoliaSearch requires an apiKey

![image](https://user-images.githubusercontent.com/4994260/43366439-c949352e-9370-11e8-8d5b-d11d6749e40a.png)

This also blocks admin from being accessed, thus blocking user from fixing issue.

```
a:5:{i:0;s:33:"AlgoliaSearch requires an apiKey.";i:1;s:3460:"#0 /vagrant/machines/ntotankphp7/www/docroot/lib/AlgoliaSearch/Client.php(109): AlgoliaSearch\ClientContext->__construct('IEQ1QNZQ1K', '\xAB\xC9\xB7h*U\xC0d\xD5bd\x1F\xFB\xE6c...', NULL, false, NULL)
#1 /vagrant/machines/ntotankphp7/www/docroot/app/code/community/Algolia/Algoliasearch/Helper/Algoliahelper.php(46): AlgoliaSearch\Client->__construct('IEQ1QNZQ1K', '\xAB\xC9\xB7h*U\xC0d\xD5bd\x1F\xFB\xE6c...')
#2 /vagrant/machines/ntotankphp7/www/docroot/app/code/community/Algolia/Algoliasearch/Helper/Algoliahelper.php(30): Algolia_Algoliasearch_Helper_Algoliahelper->resetCredentialsFromConfig()
#3 /vagrant/machines/ntotankphp7/www/docroot/app/Mage.php(555): Algolia_Algoliasearch_Helper_Algoliahelper->__construct()
#4 /vagrant/machines/ntotankphp7/www/docroot/app/code/community/Algolia/Algoliasearch/Helper/Entity/Helper.php(22): Mage::helper('algoliasearch/a...')
#5 /vagrant/machines/ntotankphp7/www/docroot/app/Mage.php(555): Algolia_Algoliasearch_Helper_Entity_Helper->__construct()
#6 /vagrant/machines/ntotankphp7/www/docroot/app/code/community/Algolia/Algoliasearch/Model/Observer.php(26): Mage::helper('algoliasearch/e...')
#7 /vagrant/machines/ntotankphp7/www/docroot/app/code/core/Mage/Core/Model/Config.php(1357): Algolia_Algoliasearch_Model_Observer->__construct(Array)
#8 /vagrant/machines/ntotankphp7/www/docroot/app/Mage.php(471): Mage_Core_Model_Config->getModelInstance('algoliasearch/o...', Array)
#9 /vagrant/machines/ntotankphp7/www/docroot/app/Mage.php(485): Mage::getModel('algoliasearch/o...', Array)
#10 /vagrant/machines/ntotankphp7/www/docroot/app/code/core/Mage/Core/Model/App.php(1336): Mage::getSingleton('algoliasearch/o...')
#11 /vagrant/machines/ntotankphp7/www/docroot/app/Mage.php(456): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#12 /vagrant/machines/ntotankphp7/www/docroot/app/code/core/Mage/Core/Controller/Varien/Action.php(301): Mage::dispatchEvent('controller_acti...', Array)
#13 /vagrant/machines/ntotankphp7/www/docroot/app/code/core/Mage/Core/Controller/Varien/Action.php(259): Mage_Core_Controller_Varien_Action->loadLayoutUpdates()
#14 /vagrant/machines/ntotankphp7/www/docroot/app/code/core/Mage/Adminhtml/Controller/Action.php(285): Mage_Core_Controller_Varien_Action->loadLayout(NULL, true, true)
#15 /vagrant/machines/ntotankphp7/www/docroot/app/code/core/Mage/Adminhtml/controllers/Sales/OrderController.php(59): Mage_Adminhtml_Controller_Action->loadLayout()
#16 /vagrant/machines/ntotankphp7/www/docroot/app/code/core/Mage/Adminhtml/controllers/Sales/OrderController.php(94): Mage_Adminhtml_Sales_OrderController->_initAction()
#17 /vagrant/machines/ntotankphp7/www/docroot/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Sales_OrderController->indexAction()
#18 /vagrant/machines/ntotankphp7/www/docroot/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#19 /vagrant/machines/ntotankphp7/www/docroot/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#20 /vagrant/machines/ntotankphp7/www/docroot/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#21 /vagrant/machines/ntotankphp7/www/docroot/app/Mage.php(691): Mage_Core_Model_App->run(Array)
#22 /vagrant/machines/ntotankphp7/www/docroot/index.php(95): Mage::run('', 'store')
#23 {main}";s:3:"url";s:73:"/index.php/manage/sales_order/index/key/5135c8db5a4fa857aa2db09c600c3ef2/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}
```

settings in core_config_data was disabled vai sql, but problem remains:

algoliasearch/credentials/enable_frontend = 0
algoliasearch/credentials/enable_backend = 0

algoliasearch/credentials/application_id has a value
algoliasearch/credentials/search_only_api_key has a value
algoliasearch/credentials/api_key has a value

These worked in 1.6.0

**Bug: What is the expected behavior?**

missing or wrong API key should not throw a report exception, which kills site. 

**Bug: What is the proposed solution?**

This exception should be properly trapped, and be a message to the system.log, and allow site to continue to operate, and algolia should be disabled.

Is an exception really needed here, and should rather be a logged message to system.log 

**Feature: What is your use case for such a feature?**

Upgrade from old version to new, using composer

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Magento ce 1.9.3.7 / Algolia 1.14.0

Checking core_config_data for algolia settings, which was working on 1.6.0

**Comment by ProxiBlue** [comment]
Using mysql to remove current values from 

algoliasearch/credentials/search_only_api_key 
algoliasearch/credentials/api_key

allows site to continue.
