### ISSUE TITLE
An error occurred while saving this configuration: Invalid string of size 0 near line:1 

### ISSUE THREAD

**Issue by obsergiu** [algolia/algoliasearch-magento#1049]
Hello, 

We have upgraded to version 1.14 and recently we noticed the search wasn't performing well.
On a close investigation resultated that the `searchable attributes` and `ranking formula` is reseted every time the algolia index is reindexed.

As you can see from attached image:
![searchable_attributes_crash](https://user-images.githubusercontent.com/1486717/43411443-144b0280-9422-11e8-91ef-0320444faf15.png)

Tried to setup the proper configurations in Magento backend but I'm getting the following error:
![algolia_crash](https://user-images.githubusercontent.com/1486717/43411611-96e32a6a-9422-11e8-9e89-26c2a8befc5c.png)

On logs investigation I get the following error:
```
2018-07-30T16:51:52+00:00 DEBUG (7): Exception message: Invalid string of size 0 near line:1 column:12369
Trace: #0 /algolia_algoliasearch-magento/lib/AlgoliaSearch/Client.php(808): AlgoliaSearch\Client->doRequest(Object(AlgoliaSearch\ClientContext), 'POST', 'OX43247IHH.algo...', '/1/indexes/nws_...', NULL, Array, 1, 30)
#1 /http/algolia_algoliasearch-magento/lib/AlgoliaSearch/Index.php(1484): AlgoliaSearch\Client->request(Object(AlgoliaSearch\ClientContext), 'POST', '/1/indexes/nws_...', NULL, Array, Array, 1, 30)
#2 /http/algolia_algoliasearch-magento/app/code/community/Algolia/Algoliasearch/Helper/Algoliahelper.php(203): AlgoliaSearch\Index->batchSynonyms(Array, true, true)
#3 /http/algolia_algoliasearch-magento/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php(437): Algolia_Algoliasearch_Helper_Algoliahelper->setSynonyms('nws_ie_en_produ...', Array)
#4 /http/algolia_algoliasearch-magento/app/code/community/Algolia/Algoliasearch/Helper/Data.php(102): Algolia_Algoliasearch_Helper_Entity_Producthelper->setSettings('5', false)
#5 /http/algolia_algoliasearch-magento/app/code/community/Algolia/Algoliasearch/Model/Observer.php(52): Algolia_Algoliasearch_Helper_Data->saveConfigurationToAlgolia('5', false)
#6 /http/algolia_algoliasearch-magento/app/code/community/Algolia/Algoliasearch/Model/Observer.php(39): Algolia_Algoliasearch_Model_Observer->saveSettings()
#7 http/app/code/core/Mage/Core/Model/App.php(1358): Algolia_Algoliasearch_Model_Observer->configSaved(Object(Varien_Event_Observer))
#8 http/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Networld_Algolia_Model_Observer), 'configSaved', Object(Varien_Event_Observer))
#9 http/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('admin_system_co...', Array)
#10 http/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(178): Mage::dispatchEvent('admin_system_co...', Array)
#11 http/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_ConfigController->saveAction()
#12 http/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('save')
#13 http/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#14 http/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#15 http/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#16 http/index.php(83): Mage::run('nws_uk', 'website')
```

I understand it might be our magento setup or it might be the fact we're using a multistore.
It would be very useful to get at least some feedback.

Thank you.

**Comment by obsergiu** [comment]
After digging a bit it seems it's crashing when it try to update the synonyms

```/1/indexes/nws_ie_en_products/synonyms/batch?replaceExistingSynonyms=true&forwardToReplicas=true```

error being: 
```Invalid string of size 0 near line:1 column:12369```

**Comment by obsergiu** [comment]
The extension is poorly writen - the upper problem was caused by customer adding an extra coma in synonyms field.

How is possible not to validate the info and make sure it's not breaking the modlule. 
Also,  I'm very disappinted for lack of feedback.

**Comment by kartinka** [comment]
@obsergiu thank you very much for the tip with comma! You literally saved me tons of time and grey hair today!
