### ISSUE TITLE
Algolia Search Queue Runner Indexer throws an exception (socket problems)

### ISSUE THREAD

**Issue by gpaddis** [algolia/algoliasearch-magento#1087]
Hi, 

I have a problem reindexing **algolia_queue_runner** with `php -f indexer.php -- -reindex algolia_queue_runner`. 
After ca. 20 seconds, the indexer throws 2-3 exceptions as follows:

```
Algolia Search Queue Runner index process unknown error:
exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user '******'@'localhost' (using password: YES)' in /path/to/magento/lib/Zend/Db/Adapter/Pdo/Abstract.php:129
Stack trace:
#0 /path/to/magento/lib/Zend/Db/Adapter/Pdo/Abstract.php(129): PDO->__construct('mysql:dbname=**...', '******', '*******', Array)
#1 /path/to/magento/lib/Zend/Db/Adapter/Pdo/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect()
#2 /path/to/magento/lib/Varien/Db/Adapter/Pdo/Mysql.php(396): Zend_Db_Adapter_Pdo_Mysql->_connect()
#3 /path/to/magento/lib/Zend/Db/Adapter/Abstract.php(460): Varien_Db_Adapter_Pdo_Mysql->_connect()
#4 /path/to/magento/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT RELEASE_...', Array)
#5 /path/to/magento/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SELECT RELEASE_...', Array)
#6 /path/to/magento/app/code/core/Mage/Index/Model/Resource/Helper/Mysql4.php(72): Varien_Db_Adapter_Pdo_Mysql->query('SELECT RELEASE_...', Array)
#7 /path/to/magento/app/code/core/Mage/Index/Model/Lock/Storage/Db.php(84): Mage_Index_Model_Resource_Helper_Mysql4->releaseLock('*****...')
#8 /path/to/magento/app/code/core/Mage/Index/Model/Lock.php(208): Mage_Index_Model_Lock_Storage_Db->releaseLock('index_process_1...')
#9 /path/to/magento/app/code/core/Mage/Index/Model/Lock.php(181): Mage_Index_Model_Lock->_releaseLockDb('index_process_1...')
#10 /path/to/magento/app/code/core/Mage/Index/Model/Process.php(469): Mage_Index_Model_Lock->releaseLock('index_process_1...', NULL)
#11 /path/to/magento/app/code/core/Mage/Index/Model/Process.php(223): Mage_Index_Model_Process->unlock()
#12 /path/to/magento/app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll()
#13 /path/to/magento/shell/indexer.php(168): Mage_Index_Model_Process->reindexEverything()
#14 /path/to/magento/shell/indexer.php(216): Mage_Shell_Compiler->run()
#15 {main}
```

All the other indexes are running fine, it's just this one that is causing the full reindex process to break. 

I am using the module version **1.14.1** on **Magento 1.9.3.10** [patched](https://magento.com/tech-resources/download#download2240) on **PHP 7.2**. One important detail: Magento accesses the MySQL database via **socket connection** (even though the exception says "localhost": maybe this is the problem?). I could reproduce this issue nowhere else.

**Comment by gpaddis** [comment]
After a deep debugging session, I came to analyze the content of $dsn in 
 `magento/lib/Zend/Db/Adapter/Pdo/Abstract.php`, Line 123, where the connection parameters are set. This way I could analyze the string by adding the following line:

```php
echo "$dsn, {$this->_config['username']}, {$this->_config['password']}\n";
```

The indexer performs **3 calls**: the first one is correct, the last two contain **an empty host= parameter** that breaks everything causing the "Access Denied" error:
```
magento/shell$ php indexer.php --reindex algolia_queue_runner
mysql:dbname=magento;port=3307;initStatements=SET NAMES utf8;model=mysql4;type=pdo_mysql;pdoType=;active=1;unix_socket=/tmp/mysql5.sock, username, password
mysql:dbname=magento;port=3307;initStatements=SET NAMES utf8;model=mysql4;type=pdo_mysql;pdoType=;active=1;unix_socket=/tmp/mysql5.sock;host=, username, password
mysql:dbname=magento;port=3307;initStatements=SET NAMES utf8;model=mysql4;type=pdo_mysql;pdoType=;active=1;unix_socket=/tmp/mysql5.sock;host=, username, password
```

To test if this was the problem, I replaced `;host=` with `;host=localhost` in the connection string:

```php
$dsn=str_replace(';host=', ';host=localhost', $dsn);
```

After this replacement, the indexer worked as expected - this time, I got only **2 requests to the database:**

```
magento/shell$ php indexer.php --reindex algolia_queue_runner
mysql:dbname=magento;port=3307;initStatements=SET NAMES utf8;model=mysql4;type=pdo_mysql;pdoType=;active=1;unix_socket=/tmp/mysql5.sock, username, password
mysql:dbname=magento;port=3307;initStatements=SET NAMES utf8;model=mysql4;type=pdo_mysql;pdoType=;active=1;unix_socket=/tmp/mysql5.sock;host=localhost, username, password
Algolia Search Queue Runner index was rebuilt successfully in 00:00:19
```

Of course this cannot be a definitive solution to the problem, since I can't just hack the core Magento PDO-Adapter in the live shop without knowing the possible consequences!

Setting the following parameters in the php.ini didn't help as well (I am still getting `host=` in the connection string):
```
mysql.default_host="localhost"
mysqli.default_host="localhost"
mysql.default_port=3307
mysqli.default_port=3307
```
The question is: **why is this particular indexer establishing two different connections** with the database? 
Where and how can this be fixed?

**Comment by gpaddis** [comment]
**We managed to solve the issue** with the help of the hosting provider, even though we haven't found the exact cause of the error.

The **solution** first: in our `local.xml` file we used to have the path to the socket file (e.g. `<host><![CDATA[/tmp/mysql.sock]]></host>`). After changing that to `<host><![CDATA[127.0.0.1]]></host>`, the indexer runs smoothly until the end without any exceptions and the shop still works as expected.

I don't have time to get deeper and debug why everything but this indexer was running fine with the socket configuration as well, but IMHO there must be some subtle difference in the way this indexer works that causes problems when Magento uses a socket to connect to the database.
