### ISSUE TITLE
Wrong renderer in adminhtml grid

### ISSUE THREAD

**Issue by MarcoPierozziTriboo** [algolia/algoliasearch-magento#1131]
There is an issue with the column Data inside ```app/code/community/Algolia/Algoliasearch/Block/Adminhtml/Indexingqueue/Grid/Renderer/Json.php```

```php
$this->addColumn('data', array(
     'header' => Mage::helper('algoliasearch')->__('Data'),
     'index' => 'data',
     'renderer' => 'Algolia_Algoliasearch_Block_Adminhtml_IndexingQueue_Grid_Renderer_Json'
));
```

should be

```php 
 'renderer' => 'algoliasearch/adminhtml_indexingqueue_grid_renderer_json'
```

**Comment by damcou** [comment]
Hello @MarcoPierozziTriboo ,

Do you get any error when you try to display the grid ?

**Comment by MarcoPierozziTriboo** [comment]
Short:
```
Mage_Core_Exception: Invalid block type: Algolia_Algoliasearch_Block_Adminhtml_IndexingQueue_Grid_Renderer_Json
```

Just some more info:
Magento version 1.9.4.1
PHP 7.0

Stack:
```
2019-05-08T15:45:29+00:00 ERR (3): 
Mage_Core_Exception: Invalid block type: Algolia_Algoliasearch_Block_Adminhtml_IndexingQueue_Grid_Renderer_Json in /var/www/html/app/Mage.php:606
Stack trace:
#0 /var/www/html/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/html/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('Algolia_Algolia...', Array)
#2 /var/www/html/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Column.php(290): Mage_Core_Model_Layout->createBlock('algoliasearch/a...')
#3 /var/www/html/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Column.php(67): Mage_Adminhtml_Block_Widget_Grid_Column->getRenderer()
#4 /var/www/html/app/design/adminhtml/default/default/template/widget/grid.phtml(122): Mage_Adminhtml_Block_Widget_Grid_Column->getHtmlProperty()
#5 /var/www/html/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/html/a...')
#6 /var/www/html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#7 /var/www/html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#8 /var/www/html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#9 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Template->_toHtml()
#10 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#11 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('grid', true)
#12 /var/www/html/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Container.php(77): Mage_Core_Block_Abstract->getChildHtml('grid')
#13 /var/www/html/app/design/adminhtml/default/default/template/widget/grid/container.phtml(36): Mage_Adminhtml_Block_Widget_Grid_Container->getGridHtml()
#14 /var/www/html/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/html/a...')
#15 /var/www/html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#16 /var/www/html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#17 /var/www/html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#18 /var/www/html/app/code/core/Mage/Adminhtml/Block/Widget/Container.php(308): Mage_Adminhtml_Block_Template->_toHtml()
#19 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Widget_Container->_toHtml()
#20 /var/www/html/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#21 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Text_List->_toHtml()
#22 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#23 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#24 /var/www/html/app/design/adminhtml/default/default/template/page.phtml(74): Mage_Core_Block_Abstract->getChildHtml('content')
#25 /var/www/html/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/html/a...')
#26 /var/www/html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#27 /var/www/html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#28 /var/www/html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#29 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Template->_toHtml()
#30 /var/www/html/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#31 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#32 /var/www/html/app/code/community/Algolia/Algoliasearch/controllers/Adminhtml/Algoliasearch/IndexingqueueController.php(24): Mage_Core_Controller_Varien_Action->renderLayout()
#33 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Algolia_Algoliasearch_Adminhtml_Algoliasearch_IndexingqueueController->indexAction()
#34 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#35 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#36 /var/www/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#37 /var/www/html/app/Mage.php(694): Mage_Core_Model_App->run(Array)
#38 /var/www/html/index.php(110): Mage::run('', 'store')
#39 {main}
```

**Comment by MarcoPierozziTriboo** [comment]
I think i have found the possible solution:

Class name is
```Algolia_Algoliasearch_Block_Adminhtml_Indexingqueue_Grid_Renderer_Json``` but on the renderer is defined as 
```Algolia_Algoliasearch_Block_Adminhtml_IndexingQueue_Grid_Renderer_Json``` (look at the camel case in IndexingQueue) so both

```php 
'renderer' => 'algoliasearch/adminhtml_indexingqueue_grid_renderer_json'
```

and 

```php
 'renderer' => 'Algolia_Algoliasearch_Block_Adminhtml_Indexingqueue_Grid_Renderer_Json'
```

are valid ways to solve this

**Comment by damcou** [comment]
@MarcoPierozziTriboo ,

You're right, there was a missing uppercased letter that can generate issues on some servers.
I created the PR and the fix will be available on the next release.

Thanks a lot for spotting this ;)

Best.
Damien

**Comment by MarcoPierozziTriboo** [comment]
You're welcome! thanks for the fast answer :)

**Comment by bsuravech** [comment]
This has been merged into the develop branch and will be included in the next release. Thanks for reporting!
