### ISSUE TITLE
You cannot define a correlation name 'at_stock_qty' more than once

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#787]
@JanPetr hi, 

we have updated algolia and stareted receiving error in logs. The queue sends 100 products, but only 10-20 are getting reindexed and we get such error:

2017-03-13T18:44:23+00:00 DEBUG (7): Queue processing  [KO]: Mage::getSingleton(algoliasearch/observer)->rebuildProductIndex({"store_id":"1","product_ids":["5924","5925","5926","5944","5946","5947","5948","5949","5950","5951","5952","5953","5954","5955","5957","5958","5959","5960","5961","5962","5963","5964","5965","5966","5967","5968","5969","5970","5971","5972","5973","5974","5975","5977","5978","5979","5980","5981","5982","5983","6016","6017","6018","6019","6020","6021","6022","6023","6024","6025","6026","6027","6028","6029","6030","6031","6032","6033","6034","6035","6036","6037","6038","6039","6040","6041","6042","6043","6044","6045","6046","6047","6048","6049","6050","6051","6052","6053","6054","6055","6056","6057","6058","6059","6060","6061","6062","6063","6064","6065","6066","6067","6068","6069","6070","6087","6088","6089","6090","6091","6258","6259","6260","6261","6262","6263","6264","6265","6266","6267","6268","6269","6270","6376","6377","6378","6379","6380","6381","6382"]})
2017-03-13T18:44:23+00:00 DEBUG (7): 2017-03-13T18:44:23+00:00 ERROR: Zend_Db_Select_Exception: 'You cannot define a correlation name 'at_stock_qty' more than once' in /domains/golfdiscount.com/http/lib/Zend/Db/Select.php:808
Stack trace:
#0 /domains/golfdiscount.com/http/lib/Varien/Db/Select.php(281): Zend_Db_Select->_join('left join', Array, '(at_stock_qty.`...', Array, NULL)
#1 /domains/golfdiscount.com/http/lib/Zend/Db/Select.php(357): Varien_Db_Select->_join('left join', Array, '(at_stock_qty.`...', Array, NULL)
#2 /domains/golfdiscount.com/http/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(734): Zend_Db_Select->joinLeft(Array, '(at_stock_qty.`...', Array)
#3 /domains/golfdiscount.com/http/app/code/community/Algolia/Algoliasearch/Helper/Data.php(514): Mage_Eav_Model_Entity_Collection_Abstract->joinField('stock_qty', 'cataloginventor...', 'qty', 'product_id=enti...', '{{table}}.stock...', 'left')
#4 /domains/golfdiscount.com/http/app/code/community/Algolia/Algoliasearch/Helper/Data.php(324): Algolia_Algoliasearch_Helper_Data->rebuildStoreProductIndexPage('1', Object(Ayasoftware_PriceIndex_Catalog_Model_Resource_Eav_Mysql4_Product_Collection), 2, '50', Object(Varien_Object), Array)
#5 /domains/golfdiscount.com/http/app/code/community/Algolia/Algoliasearch/Model/Observer.php(215): Algolia_Algoliasearch_Helper_Data->rebuildStoreProductIndex('1', Array)
#6 /domains/golfdiscount.com/http/app/code/community/Algolia/Algoliasearch/Model/Queue.php(223): Algolia_Algoliasearch_Model_Observer->rebuildProductIndex(Object(Varien_Object))
#7 /domains/golfdiscount.com/http/app/code/community/Algolia/Algoliasearch/Model/Queue.php(59): Algolia_Algoliasearch_Model_Queue->run('20')
#8 /domains/golfdiscount.com/http/app/code/community/Algolia/Algoliasearch/Model/Indexer/Algoliaqueuerunner.php(74): Algolia_Algoliasearch_Model_Queue->runCron()
#9 /domains/golfdiscount.com/http/app/code/core/Mage/Index/Model/Process.php(210): Algolia_Algoliasearch_Model_Indexer_Algoliaqueuerunner->reindexAll()
#10 /domains/golfdiscount.com/http/app/code/core/Mage/Index/Model/Process.php(258): Mage_Index_Model_Process->reindexAll()
#11 /domains/golfdiscount.com/http/shell/indexer.php(166): Mage_Index_Model_Process->reindexEverything()
#12 /domains/golfdiscount.com/http/shell/indexer.php(212): Mage_Shell_Compiler->run()
#13 {main}

Could you, please, help with advice?

**Comment by Mobecls** [comment]
It seems that these steps can reproduce the issue:

1. set Max number of element per indexing job = 120
2. wait till you get in queue severla id's with 120 products
3. set Max number of element per indexing job = 50

And you'll get an error. Seems like because of that rebuildStoreProductIndexPage() being called recursevily.

**Comment by JanPetr** [comment]
Hello @Mobecls,

I tried to reproduce, but I couldn't, everything works OK.
Could you try it with the latest version if you still experience the issue? Let me know.

**Comment by Mobecls** [comment]
Hello @JanPetr, the exact problem was connected to the cache issues. 

As for the reindexing - we are still verifying it. If we still have any issues, I will create separate issue.
