### ISSUE TITLE
Lock wait timeout exceeded while reindexing 

### ISSUE THREAD

**Issue by alexbogias** [algolia/algoliasearch-magento#912]
I am getting this log on my exception.log. I dont know if its my setup or a general algolia issue, The attribute with id 98 which is mentioned is url_path which I think that is created by algolia. I dont see it in my Manage Attributes screen.

```
DEBUG (7): Exception message: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction, query was: UPDATE `catalog_product_flat_2` AS `e`
 LEFT JOIN `catalog_product_entity_varchar` AS `t1` ON e.entity_id = t1.entity_id AND t1.entity_type_id = 4 AND t1.attribute_id = 98 AND t1.store_id = 0
 LEFT JOIN `catalog_product_entity_varchar` AS `t2` ON e.entity_id = t2.entity_id AND t2.entity_type_id = 4 AND t2.attribute_id = 98 AND t2.store_id = 2
SET `e`.`url_path` = IF(t2.value_id > 0, t2.value, t1.value)
Trace: #0 /home/xxxx/public_html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/xxxx/public_html/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /home/xxxx/public_html/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /home/xxxx/public_html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE `catalog...', Array)
#4 /home/xxxx/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE `catalog...', Array)
#5 /home/xxxx/public_html/app/code/core/Mage/Catalog/Model/Resource/Product/Flat/Indexer.php(1001): Varien_Db_Adapter_Pdo_Mysql->query('UPDATE `catalog...')
#6 /home/xxxx/public_html/app/code/core/Mage/Catalog/Model/Resource/Product/Flat/Indexer.php(1024): Mage_Catalog_Model_Resource_Product_Flat_Indexer->updateAttribute(Object(Mage_Catalog_Model_Resource_Eav_Attribute), 2, NULL)
#7 /home/xxxx/public_html/app/code/core/Mage/Catalog/Model/Resource/Product/Flat/Indexer.php(132): Mage_Catalog_Model_Resource_Product_Flat_Indexer->updateEavAttributes(2)
#8 /home/xxxx/public_html/app/code/core/Mage/Catalog/Model/Resource/Product/Flat/Indexer.php(1392): Mage_Catalog_Model_Resource_Product_Flat_Indexer->rebuild(Object(Afternet_PricesPrecision_Model_Core_Store))
#9 /home/xxxx/public_html/app/code/core/Mage/Catalog/Model/Product/Flat/Indexer.php(296): Mage_Catalog_Model_Resource_Product_Flat_Indexer->reindexAll()
#10 /home/xxxx/public_html/app/code/core/Mage/Catalog/Model/Product/Indexer/Flat.php(350): Mage_Catalog_Model_Product_Flat_Indexer->reindexAll()
#11 /home/xxxx/public_html/app/code/core/Mage/Index/Model/Process.php(212): Mage_Catalog_Model_Product_Indexer_Flat->reindexAll()
#12 /home/xxxx/public_html/app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll()
#13 /home/xxxx/public_html/app/code/core/Mage/Index/controllers/Adminhtml/ProcessController.php(127): Mage_Index_Model_Process->reindexEverything()
#14 /home/xxxx/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Index_Adminhtml_ProcessController->reindexProcessAction()
#15 /home/xxxx/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('reindexProcess')
#16 /home/xxxx/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#17 /home/xxxx/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#18 /home/xxxx/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#19 /home/xxxx/public_html/index.php(83): Mage::run('', 'store')
#20 {main}

```

**Comment by JanPetr** [comment]
Hello Alex,

according the error you pasted here, it happens when you reindex `Mage_Catalog_Model_Product_Indexer_Flat` and not any Algolia indexers.
Did I miss something? Is it Algolia indexer which triggers the error? Do you know which one?

**Comment by alexbogias** [comment]
Hello @JanPetr,
I thought that "url_path" attribute was created by algolia exension but i now saw it in other magento installation without algolia. You can close this ticket if you think that isnt related.

**Comment by JanPetr** [comment]
Thanks for coming back to me Alex!
No, the extension doesn't create such attribute. So I'm closing the issue, but feel free to re-open! 💯
