### ISSUE TITLE
Cannot update CMS pages

### ISSUE THREAD

**Issue by greatwitenorth** [algolia/algoliasearch-magento#926]
When I try to update a cms page in the admin and click Save I get the following error in the UI:
```
An error occurred while saving the page.
```

When I check the exception log I see this:
```
2017-09-26T14:55:01+00:00 DEBUG (7): Exception message: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created' in 'field list', query was: INSERT INTO `algoliasearch_queue` (`created`, `class`, `method`, `data`, `data_size`, `pid`) VALUES (?, ?, ?, ?, ?, ?)
Trace: #0 /home/magento/production/releases/62/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/magento/production/releases/62/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /home/magento/production/releases/62/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /home/magento/production/releases/62/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `al...', Array)
#4 /home/magento/production/releases/62/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `al...', Array)
#5 /home/magento/production/releases/62/lib/Zend/Db/Adapter/Abstract.php(576): Varien_Db_Adapter_Pdo_Mysql->query('INSERT INTO `al...', Array)
#6 /home/magento/production/releases/62/vendor/algolia/algoliasearch-magento/app/code/community/Algolia/Algoliasearch/Model/Queue.php(61): Zend_Db_Adapter_Abstract->insert('algoliasearch_q...', Array)
#7 /home/magento/production/releases/62/vendor/algolia/algoliasearch-magento/app/code/community/Algolia/Algoliasearch/Model/Resource/Engine.php(47): Algolia_Algoliasearch_Model_Queue->add('algoliasearch/o...', 'rebuildPageInde...', Array, 1)
#8 /home/magento/production/releases/62/vendor/algolia/algoliasearch-magento/app/code/community/Algolia/Algoliasearch/Model/Resource/Engine.php(107): Algolia_Algoliasearch_Model_Resource_Engine->addToQueue('algoliasearch/o...', 'rebuildPageInde...', Array, 1)
#9 /home/magento/production/releases/62/vendor/algolia/algoliasearch-magento/app/code/community/Algolia/Algoliasearch/Model/Observer.php(105): Algolia_Algoliasearch_Model_Resource_Engine->rebuildPages(Array, '13')
#10 /home/magento/production/releases/62/app/code/core/Mage/Core/Model/App.php(1358): Algolia_Algoliasearch_Model_Observer->savePage(Object(Varien_Event_Observer))
#11 /home/magento/production/releases/62/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Algolia_Algoliasearch_Model_Observer), 'savePage', Object(Varien_Event_Observer))
#12 /home/magento/production/releases/62/app/Mage.php(456): Mage_Core_Model_App->dispatchEvent('cms_page_save_b...', Array)
#13 /home/magento/production/releases/62/app/code/core/Mage/Core/Model/Abstract.php(391): Mage::dispatchEvent('cms_page_save_b...', Array)
#14 /home/magento/production/releases/62/app/code/core/Mage/Core/Model/Abstract.php(316): Mage_Core_Model_Abstract->_beforeSave()
#15 /home/magento/production/releases/62/app/code/core/Mage/Adminhtml/controllers/Cms/PageController.php(150): Mage_Core_Model_Abstract->save()
#16 /home/magento/production/releases/62/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Cms_PageController->saveAction()
#17 /home/magento/production/releases/62/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('save')
#18 /home/magento/production/releases/62/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#19 /home/magento/production/releases/62/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#20 /home/magento/production/releases/62/app/Mage.php(692): Mage_Core_Model_App->run(Array)
#21 /home/magento/production/releases/62/index.php(83): Mage::run('base', 'website')
#22 {main}
```

Is there an issue with Algolia and updating CMS pages?

**Comment by JanPetr** [comment]
Hello, it looks like you just upgraded to the latest version of the extension. And the DB migration wasn't run correctly. Can you apply [this fix](https://github.com/algolia/algoliasearch-magento/issues/918#issuecomment-330801701)?
